######################################################################
# Automatically generated by qmake (2.01a) Mon Aug 27 15:02:08 2012
######################################################################

TEMPLATE = app
TARGET =
DEPENDPATH += .
INCLUDEPATH += .
QT += network
CONFIG += crypto

# Input
HEADERS += main.hh
HEADERS += server.hh
HEADERS += resource_manager.hh

SOURCES += main.cc
SOURCES += server.cc
SOURCES += resource_manager.cc
